<?php

namespace AppBundle\Repository;

/**
 * BookingStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
