<?php

namespace AppBundle\Repository;

/**
 * BookingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
