<?php

namespace AppBundle\Repository;

/**
 * BuisnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuisnessRepository extends \Doctrine\ORM\EntityRepository
{
}
