<?php

namespace AppBundle\Repository;

/**
 * ComissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComissionsRepository extends \Doctrine\ORM\EntityRepository
{
}
