<?php

namespace AppBundle\Repository;

/**
 * CorporateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporateRepository extends \Doctrine\ORM\EntityRepository
{
}
