<?php

namespace AppBundle\Repository;

/**
 * DeliveryTownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryTownRepository extends \Doctrine\ORM\EntityRepository
{
}
