<?php

namespace AppBundle\Repository;

/**
 * DeliveryAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
