<?php

namespace AppBundle\Repository;

/**
 * DeliveryFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
