<?php

namespace AppBundle\Repository;

/**
 * MenuOptionProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuOptionProductRepository extends \Doctrine\ORM\EntityRepository
{
}
