<?php

namespace AppBundle\Repository;

/**
 * MenuOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
