<?php

namespace AppBundle\Repository;

/**
 * MenuSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuSizeRepository extends \Doctrine\ORM\EntityRepository
{
}
