<?php

namespace AppBundle\Repository;

/**
 * OptionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
