<?php

namespace AppBundle\Repository;

/**
 * OrderStatusHourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusHourRepository extends \Doctrine\ORM\EntityRepository
{
}
