<?php

namespace AppBundle\Repository;

/**
 * OrderMenuProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMenuProductRepository extends \Doctrine\ORM\EntityRepository
{
}
