<?php

namespace AppBundle\Repository;

/**
 * ProductSupplementGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSupplementGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
