<?php

namespace AppBundle\Repository;

/**
 * ProductOptionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
