<?php

namespace AppBundle\Repository;

/**
 * RestaurantUserRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantUserRankRepository extends \Doctrine\ORM\EntityRepository
{
}
