<?php

namespace AppBundle\Repository;

/**
 * RestaurantUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantUserRepository extends \Doctrine\ORM\EntityRepository
{
}
