<?php

namespace AppBundle\Repository;

/**
 * RestaurantPaymentModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantPaymentModeRepository extends \Doctrine\ORM\EntityRepository
{
}
