<?php

namespace AppBundle\Repository;

/**
 * ScheduleOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
