<?php

namespace AppBundle\Repository;

/**
 * ScheduleFreakStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleFreakStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
