<?php

namespace AppBundle\Repository;

/**
 * ScheduleBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleBookingRepository extends \Doctrine\ORM\EntityRepository
{
}
