<?php

namespace AppBundle\Repository;

/**
 * SpecialFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
