<?php

namespace AppBundle\Repository;

/**
 * StandardFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
