<?php

namespace AppBundle\Repository;

/**
 * SupplementGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
