<?php

namespace AppBundle\Repository;

/**
 * TypeOfCuisineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfCuisineRepository extends \Doctrine\ORM\EntityRepository
{
}
