<?php

namespace AppBundle\Repository;

/**
 * VATRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VATRepository extends \Doctrine\ORM\EntityRepository
{
}
